### ISSUE TITLE
Fails on Linux in _get_hz_string_from_brand

### ISSUE THREAD

**Issue by techtonik** [workhorsy/py-cpuinfo#11]
```
Traceback (most recent call last):
  ...
    info = get_cpu_info()
  File "cpuinfo.py", line 1195, in get_cpu_info
    info = get_cpu_info_from_proc_cpuinfo()
  File "cpuinfo.py", line 804, in get_cpu_info_from_proc_cpuinfo
    scale, hz_advertised = _get_hz_string_from_brand(processor_brand)
  File "cpuinfo.py", line 82, in _get_hz_string_from_brand
    hz_brand = hz_brand.split('@')[1]
IndexError: list index out of range
```

processor_brand string is `Intel(R) Pentium(R) D CPU 3.20GHz`

**Comment by workhorsy** [comment]
Fixed by fe57ae91d7db4159e4bbc61cbbd65677820ab17f
