### ISSUE TITLE
Error when running get_system_info.py

### ISSUE THREAD

**Issue by adamsitnik** [workhorsy/py-cpuinfo#110]
Hello!

I tried to get the CPU info using this awesome library, but I have failed. Then I tried to run `get_system_info.py` to report a bug. But I have failed too ;)

```log
+ git clone https://github.com/workhorsy/py-cpuinfo.git
Cloning into 'py-cpuinfo'...
+ python3.5 py-cpuinfo/tools/get_system_info.py
Traceback (most recent call last):
  File "py-cpuinfo/tools/get_system_info.py", line 163, in <module>
    returncode, output = run_and_get_stdout(['wmic', 'os', 'get', 'Version'])
  File "py-cpuinfo/tools/get_system_info.py", line 51, in run_and_get_stdout
    p1 = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'wmic'
```

* CPU architecture: arm64
* Operating System: ubuntu 16.04
* Python version: 3.5
* Version of py-cpuinfo: 4.0

**Comment by workhorsy** [comment]
I'm going to rename this bug, to be more clear in the change log.
