### ISSUE TITLE
Exception: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.

### ISSUE THREAD

**Issue by gMan1990** [workhorsy/py-cpuinfo#141]
# In your bug report please include:
* Python 3.7.7
* py-cpuinfo   5.0.0

```plain
Host Name:                 WIN-45DJEBK8RU0
OS Name:                   Microsoft Windows Server 2016 Datacenter
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00377-90926-43858-AA233
Original Install Date:     2019/8/13, 13:34:51
System Boot Time:          2020/5/18, 13:40:55
System Manufacturer:       HP
System Model:              ProLiant DL580 G7
System Type:               x64-based PC
Processor(s):              4 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 47 Stepping 2 GenuineIntel ~1866 Mhz
                           [02]: Intel64 Family 6 Model 47 Stepping 2 GenuineIntel ~1866 Mhz
                           [03]: Intel64 Family 6 Model 47 Stepping 2 GenuineIntel ~1866 Mhz
                           [04]: Intel64 Family 6 Model 47 Stepping 2 GenuineIntel ~1866 Mhz
BIOS Version:              HP P65, 2012/12/3
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             zh-cn;Chinese (China)
Input Locale:              zh-cn;Chinese (China)
Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
Total Physical Memory:     131,062 MB
Available Physical Memory: 125,407 MB
Virtual Memory: Max Size:  150,518 MB
Virtual Memory: Available: 141,862 MB
Virtual Memory: In Use:    8,656 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\WIN-45DJEBK8RU0
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

----
```plain
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python37\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python37\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Program Files\Python37\lib\site-packages\cpuinfo\__init__.py", line 7, in <module>
    from cpuinfo.cpuinfo import *
  File "C:\Program Files\Python37\lib\site-packages\cpuinfo\cpuinfo.py", line 2257, in <module>
    _check_arch()
  File "C:\Program Files\Python37\lib\site-packages\cpuinfo\cpuinfo.py", line 232, in _check_arch
    raise Exception("py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.")
Exception: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.
```

**Comment by workhorsy** [comment]
Can you tell me the output of:
```python
import platform
print(platform.machine())
```

Can you also attach the "system_info.txt" file generated by this script?

```bash
python tools/get_system_info.py
```

**Comment by gMan1990** [comment]
```plain
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'AMD64'
>>>
```
<img width="402" alt="WX20200520-113041@2x" src="https://user-images.githubusercontent.com/5050994/82401807-60018500-9a8d-11ea-987b-58266648a04d.png">

**Comment by workhorsy** [comment]
Can you also attach the "system_info.txt" file generated by this script?

```bash
python tools/get_system_info.py
```

**Comment by gMan1990** [comment]
[system_info.txt](https://github.com/workhorsy/py-cpuinfo/files/4672736/system_info.txt)

**Comment by workhorsy** [comment]
It looks like platform.machine is returning invalid results for you. In both cpuinfo.py and the get_system_info.py platform.machine should be returning something like "AMD64". Instead it is returning "" or None. Do you know why this would be changed on your machine?

**Comment by workhorsy** [comment]
Did this solve your problem? Or do you need more help?

**Comment by gMan1990** [comment]
@workhorsy
> Do you know why this would be changed on your machine?

I don't know.
> Did this solve your problem?

No.

**Comment by gMan1990** [comment]
@workhorsy ok, I maybe know this problem.
1. install `python` in windows (and pip, py-cpuinfo)
    - add python to PATH
2. install cygwin in windows
    - install `python37-pip` in cygwin (and py-cpuinfo)
    - install `openssh` in cygwin
3. open cygwin and run `/usr/sbin/sshd`
4. connect it with ssh

```text
> type python
python is /cygdrive/c/Program Files/Python37/python
> python -m cpuinfo
Traceback (most recent call last):

> type python3.7
python3.7 is /bin/python3.7
> python3.7 -m cpuinfo
Python Version: 3.7.7.final.0 (64 bit)
```

5. open cmd and run `python -m cpuinfo` is ok

**Comment by workhorsy** [comment]
The wrong CPU core count looks like a duplicate of #90 .
