### ISSUE TITLE
CPUID breaks test suite when SE Linux is on (Fedora 25)

### ISSUE THREAD

**Issue by pnemade** [workhorsy/py-cpuinfo#53]
I tried to build new update 0.2.6 on fedora 25 and here is what I get the output
https://kojipkgs.fedoraproject.org//work/tasks/3355/18353355/build.log which is
```
======================================================================
FAIL: test_all (test_actual.TestActual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/py-cpuinfo-0.2.6/tests/test_actual.py", line 66, in test_all
    self.assertHasResult(cpuinfo.get_cpu_info_from_cpuid())
  File "/builddir/build/BUILD/py-cpuinfo-0.2.6/tests/test_actual.py", line 14, in assertHasResult
    raise AssertionError('Expected result, but there was none.')
AssertionError: Expected result, but there was none.
----------------------------------------------------------------------
```

I am using 64bit machine.

**Comment by workhorsy** [comment]
Thanks for the report. It looks like I forgot that SE Linux prevents the call to check CPUID. I should have a fix soon.

**Comment by workhorsy** [comment]
Fixed in 013c04b24bdf286657cb2a28bb691fa1e88aecb2

**Comment by workhorsy** [comment]
@pnemade I put out 0.2.7, let me know if that fixes your problem.

**Comment by pnemade** [comment]
@workhorsy Thanks, it worked 👍
