### ISSUE TITLE
Not working on Red Flag Linux ppc64le

### ISSUE THREAD

**Issue by mcgino** [workhorsy/py-cpuinfo#56]
Hi everyone,I met a problem about py-cpuinfo to my OPENPOWER8 cpu.
When I try to use ESRALLY to stress my ES,ESRALLY say py-cpyinfo only support x86 or ARM.
Could you give me some adivce ?thanks
[root@bogon rally]# pwd
/home/test/rally
[root@bogon rally]# esrally
Traceback (most recent call last):
  File "/usr/local/bin/esrally", line 11, in <module>
    load_entry_point('esrally==0.5.3.dev0', 'console_scripts', 'esrally')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in l
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in 
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in 
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in 
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/rally
    from esrally import version, actor, config, paths, racecontrol, reporter, metrics, tr
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/racec
    from esrally.mechanic import mechanic
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/mecha
    from esrally.mechanic import supplier, provisioner, launcher
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/mecha
    from esrally.mechanic import car
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/mecha
    from esrally.utils import sysstats, console
  File "/usr/local/lib/python3.6/site-packages/esrally-0.5.3.dev0-py3.6.egg/esrally/utils
    import cpuinfo
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/py_cpuinfo-0.2.3-py3.6.egg/cpuinfo/__init_
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/py_cpuinfo-0.2.3-py3.6.egg/cpuinfo/cpuinfo
  File "/usr/local/lib/python3.6/site-packages/py_cpuinfo-0.2.3-py3.6.egg/cpuinfo/cpuinfo
Exception: py-cpuinfo currently only works on X86 and some ARM CPUs.

**Comment by workhorsy** [comment]
Right now, I don't have access to any OpenPower machines. I would like to add support, but have no way to do that right now. Any help would be appreciated.

**Comment by mcgino** [comment]
thx for your reply.My server is an OPENPOWER server and my company is an member of OP foundation.I have to face this probelm....

**Comment by workhorsy** [comment]
If you could give me the output of this script, it might give me some of the info I need to add support for OpenPower. It should generate a file called system_info.txt:

https://github.com/workhorsy/py-cpuinfo/blob/master/tools/get_system_info.py

**Comment by mcgino** [comment]
[system_info.txt](https://github.com/workhorsy/py-cpuinfo/files/843154/system_info.txt)
HI,Matthew,this attachment is the result of your script.thank you for your help.

**Comment by workhorsy** [comment]
It should be working now.
